INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME)
VALUES(3001, 'Tabcorp');
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME)
VALUES(3002, 'Bench');
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME)
VALUES(3003, 'Tata Play OTT');
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME)
VALUES(3004, 'HDFC Banking');

INSERT INTO EMPLOYEE (ID, PROJECT_ID, SALARY, JOINING_DATE, DESIGNATION, NAME)
VALUES(9001, 3001, 30000, CURRENT_TIMESTAMP, 'SSE', 'Ram pal');
INSERT INTO EMPLOYEE (ID, PROJECT_ID, SALARY, JOINING_DATE, DESIGNATION, NAME)
VALUES(9005, 3004, 60000, CURRENT_TIMESTAMP, 'ATL', 'Shivam Singh');
INSERT INTO EMPLOYEE (ID, PROJECT_ID, SALARY, JOINING_DATE, DESIGNATION, NAME)
VALUES(9008, 3002, 10000, CURRENT_TIMESTAMP, 'SE', 'Abhay Pratap');

